name: Python Package CI

on:
  push:
    branches:
      - main
      - phase2
  pull_request:
    branches:
      - main
      - phase2

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install geopandas pytest
        pip install build twine

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Build package
      run: python -m build

    - name: Upload to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*